version: "3.9"
services:
  __container__-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/__container__-debug:${TAG}
    ports:
      - 2345:2345
      - 2299:2299

  __container__:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/__container__:${TAG}
